// syncer-mobile/src/screens/Connections.jsx
import { useEffect, useState } from 'react'
import store from '../store'
import { sendUdpData } from '../service/udpService'
import { Text, View, StyleSheet, ScrollView } from 'react-native'
import { Button } from '@rneui/themed'
// import { Button } from '@rneui/base'
import { observer } from 'mobx-react'
import styles from '../styles/Connections'
import Icon from 'react-native-vector-icons/AntDesign'
import theme from '../styles/theme'
import { getIpAddress } from '../service/ipService'
import sleep from '../utils/sleep'

const MyDeviceName = observer(() => (
  <View>
    <Text style={ styles.myDeviceName }>{ store.name }</Text>
  </View>
))

const AvailableTitle = () => {
  const [searching, setSearching] = useState(false)

  useEffect(() => {
    search()
  }, [])

  /** 查找同一局域网内的设备 */
  async function search() {
    store.clearAvailableDeviceMap()

    setSearching(true)
    for (let i = 0; i < 5; i++) {
      // sendUdpData({ type: 'search' }, 5742, '239.57.42.42')
      sendUdpData({ type: 'search' }, 5742, '255.255.255.255')
      await sleep(500)
    }
    setSearching(false)
  }

  return (
    <>
      <View style={ styles.availableTitle }>
        <Text style={ styles.availableTitleText }>可用设备</Text>
        <Button loading={ searching } type="outline"
                buttonStyle={ styles.searchButton } titleStyle={ styles.searchButtonText }
                onPress={ search }>查找</Button>
      </View>
    </>
  )
}

const AvailableDevices = observer(() => {
  return (
    <ScrollView style={ styles.availableDevices }>
      {
        Array.from(store.availableDeviceMap.values()).map(device => (
          <View key={ device.uuid } style={ styles.availableDevice }>
            <Icon name={ device.device === 'desktop' ? 'iconfontdesktop' :
              device.device === 'mobile' ? 'mobile1' : 'question' } size={ 32 } color={ theme.mainTextColor } />
            <View style={ styles.availableDeviceInfo }>
              <Text style={ styles.availableDeviceName }>{ device.name }</Text>
              <Text style={ styles.availableDeviceAddress }>{ device.address }</Text>
            </View>
            <Button buttonStyle={ styles.connectButton } titleStyle={ styles.connectButtonText }
                    onPress={ () => store.connect(device) }>连接</Button>
          </View>
        ))
      }
      <Text style={ styles.tip }>请确保设备已连接至同一个 Wi-Fi 网络</Text>
    </ScrollView>
  )
})

export default function Connections() {

  return (
    <>
      <MyDeviceName />
      <AvailableTitle />
      <AvailableDevices />
    </>
  )
}

// syncer-desktop/src/views/Connections.vue
<template>
  <div class="my-device-name">
    <h1>{{ name }}</h1>
    <a-button type="text">
      <template #icon>
        <EditOutlined class="edit" />
      </template>
    </a-button>
  </div>

  <div class="available-title">
    <div>可用设备</div>
    <a-button :loading="searching" @click="search">查找</a-button>
  </div>
  <div class="available-devices">
    <a-card v-for="device in availableDeviceList" :key="device.uuid" hoverable>
      <div class="available-device">
        <div class="left">
          <DesktopOutlined v-if="device.device === 'desktop'" />
          <MobileOutlined v-else-if="device.device === 'mobile'" />
          <QuestionOutlined v-else />
        </div>
        <div class="middle">
          <div class="device-name">{{ device.name }}</div>
          <div class="device-address">{{ device.address }}</div>
        </div>
        <a-button class="right" type="primary" ghost shape="round" @click="connect(device)">连接</a-button>
      </div>
    </a-card>
    <div class="tip">请确保设备已连接至同一个 Wi-Fi 网络</div>
  </div>

  <!-- 正在连接 -->
  <a-modal :open="connecting" centered :width="400" title="正在连接" :closable="false">
    <template #footer>
      <a-button type="primary" ghost @click="store.dispatch('cancel')">取消</a-button>
    </template>
    等待 {{ target ? target.name : '' }} 接受连接请求<a-spin class="text-loading" size="small" />
  </a-modal>
</template>

<script setup>
import { sendUdpData } from '@/service/udpService'
import { useStore } from 'vuex'
import { computed, ref } from 'vue'
import { DesktopOutlined, MobileOutlined, QuestionOutlined, EditOutlined } from '@ant-design/icons-vue'
import sleep from '@/utils/sleep'

const store = useStore()
const name = computed(() => store.state.name)

const availableDeviceList = computed(() => {
  const availableDeviceList = []
  const availableDeviceMap = store.state.availableDeviceMap
  for (const uuid of availableDeviceMap.keys())
    availableDeviceList.push({ ...availableDeviceMap.get(uuid) })
  return availableDeviceList
})

const searching = ref(false)


/** 查找同一局域网内的设备 */
async function search() {
  store.commit('clearAvailableDeviceMap')

  searching.value = true
  for (let i = 0; i < 5; i++) {
    // sendUdpData({ type: 'find' }, 5742, '239.57.42.42')
    sendUdpData({ type: 'search' }, 5742, '255.255.255.255')
    await sleep(500)
  }
  searching.value = false
}

const connecting = computed(() => store.state.status === 'connecting')
const target = computed(() => store.state.target)

/** 发起连接请求 */
async function connect(device) {
  await store.dispatch('connect', device)
}

search()

</script>

<style lang="scss" scoped src="@/styles/Connections.scss" />
