// syncer-mobile/src/screens/Send.jsx
import { Image, ImageBackground, ScrollView, Text, ToastAndroid, Touchable, TouchableOpacity, View } from 'react-native'
import { useEffect, useState } from 'react'
import { Button, ButtonGroup, CheckBox, Input } from '@rneui/themed'
import { sendTcpData } from '../service/tcpService'
import store from '../store'
import { observer } from 'mobx-react'
import styles from '../styles/SendStyles'
import DocumentPicker from 'react-native-document-picker'
import RNFS from 'react-native-fs'
import Icon from 'react-native-vector-icons/AntDesign'
import sleep from '../utils/sleep'
import { Modal, modalStyles } from '../components/Modal'
import { showReceiveHistory } from '../components/ReceiveHistory'
import theme from '../styles/theme'
import { getStorage, setStorage, STORAGE_KEYS } from '../utils/storage'

export default () => {
  const [type, setType] = useState('text')

  return (
    <View>
      <Target />
      <WhiteList />
      <SelectType type={ type } setType={ setType } />
      <SendContent type={ type } />
    </View>
  )
}

const Target = observer(() => {
  const target = store.target

  const disconnect = () => {
    sendTcpData({
      type: 'disconnect'
    })
    store.disconnect()
  }

  return (
    <View style={ styles.target }>
      <Text numberOfLines={ 1 } ellipsizeMode="tail" style={ styles.targetName }>{ target.name }</Text>
      <Button type="outline" onPress={ disconnect }>断开连接</Button>
      <Button type="clear" icon={ <Icon name="filetext1" size={ 20 } color={ theme.secondaryTextColor } /> }
              containerStyle={ { marginLeft: 'auto' } } onPress={ showReceiveHistory } />
    </View>
  )
})

const WhiteList = () => {
  const [isInWhiteList, setIsInWhiteList] = useState(false)

  useEffect(() => {
    getStorage(STORAGE_KEYS.WHITE_LIST).then((whiteList) => {
      whiteList = whiteList || {}
      setIsInWhiteList(whiteList[store.target.uuid] === true)
    })
  }, [])

  async function getIsInWhiteList() {
    const whiteList = await getStorage(STORAGE_KEYS.WHITE_LIST) || {}
    setIsInWhiteList(whiteList[store.target.uuid] === true)
  }

  async function setIsInWhiteList_(isInWhiteList) {
    const whiteList = await getStorage(STORAGE_KEYS.WHITE_LIST) || {}
    if (isInWhiteList)
      whiteList[store.target.uuid] = true
    else
      delete whiteList[store.target.uuid]
    await setStorage(STORAGE_KEYS.WHITE_LIST, whiteList)
    await getIsInWhiteList()
  }

  return (
    <View style={ styles.whiteList }>
      <CheckBox checked={ isInWhiteList } size={ 20 } title="自动接受此设备的连接请求"
                onPress={ () => setIsInWhiteList_(!isInWhiteList) } />
    </View>
  )
}


const typeList = ['text', 'file', 'command']
const SelectType = ({ type, setType }) => {
  return (
    <ButtonGroup
      selectedIndex={ typeList.indexOf(type) }
      buttons={ ['发送文本', '发送文件', '发送指令'] }
      containerStyle={ styles.selectType }
      onPress={ (index) => { setType(typeList[index]) } } />
  )
}

const SendContent = observer(({ type }) => {
  switch (type) {
    case 'text':
      return <SendText />
    case 'file':
      return <SendFile />
    case 'command':
      return store.target.device === 'desktop' ? <SendCommand /> : <SendRing />
  }
})

const SendText = () => {
  const [text, setText] = useState('')

  const sendText = async () => {
    if (!text)
      return
    await sendTcpData({
      type: 'text',
      content: text,
    })
    ToastAndroid.show('发送成功', ToastAndroid.SHORT)
    setText('')
  }

  return (
    <View>
      <Text style={ styles.sendTextTitle }>待发送文本：</Text>
      <Input value={ text } multiline placeholder="请输入要发送的文本"
             inputStyle={ { fontSize: 16 } } containerStyle={ styles.inputText }
             onChangeText={ setText } />
      <Button disabled={ !text } onPress={ sendText }>发送</Button>
    </View>
  )
}

const SendFile = () => {
  const [files, setFiles] = useState([])
  const [sendingFile, setSendingFile] = useState(false)

  async function selectFile() {
    const tempFiles = await DocumentPicker.pick({
      allowMultiSelection: true,
    })
    const newFiles = []
    for (const file of tempFiles) {
      const data = await RNFS.readFile(file.uri, 'base64')
      newFiles.push({ name: file.name, data })
    }
    setFiles([...files, ...newFiles])
  }

  function removeFile(file) {
    files.splice(files.indexOf(file), 1)
    setFiles([...files])
  }

  async function sendFile() {
    if (!files.length)
      return
    setSendingFile(true)
    await sleep(0)
    await sendTcpData({
      type: 'file',
      content: files,
    })
    setSendingFile(false)
    setFiles([])
    ToastAndroid.show('发送成功', ToastAndroid.SHORT)
  }

  return (
    <>
      <View style={ styles.sendFileTitle }>
        <Text style={ styles.sendFileTitleText }>待发送文件：</Text>
        <Button onPress={ selectFile }>添加文件</Button>
      </View>
      {
        files.length > 0 &&
        <ScrollView style={ styles.fileList }>
          { files.map((file, index) => (
            <View key={ index } style={ styles.fileListItem }>
              <Text style={ styles.fileListItemName }>{ file.name }</Text>
              <Icon style={ styles.fileListItemDelete } name="delete" size={ 16 }
                    onPress={ () => { removeFile(file) } } />
            </View>
          )) }
        </ScrollView>
      }
      <Button disabled={ !files.length } loading={ sendingFile } onPress={ sendFile }>发送</Button>
    </>
  )
}

const SendCommand = () => {
  async function sendCommand(key) {
    await sendTcpData({
      type: 'command',
      content: key
    })
  }

  return (
    <>
      <View style={ styles.commandButtonWrap }>
        <TouchableOpacity style={ [styles.commandButton, { right: 50, bottom: 50 }] }
                          onPress={ () => sendCommand('up') }>
          <Text style={ styles.commandButtonText }>↑</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { right: 50, bottom: 0 }] }
                          onPress={ () => sendCommand('down') }>
          <Text style={ styles.commandButtonText }>↓</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { right: 100, bottom: 0 }] }
                          onPress={ () => sendCommand('left') }>
          <Text style={ styles.commandButtonText }>←</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { right: 0, bottom: 0 }] }
                          onPress={ () => sendCommand('right') }>
          <Text style={ styles.commandButtonText }>→</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { left: 0, bottom: 0, width: 148 }] }
                          onPress={ () => sendCommand('space') }>
          <Text style={ styles.commandButtonText }>SPACE</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { left: 0, top: 0 }] }
                          onPress={ () => sendCommand('escape') }>
          <Text style={ styles.commandButtonText }>ESC</Text>
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { left: 50, top: 0 }] }
                          onPress={ () => sendCommand('f5') }>
          <Text style={ styles.commandButtonText }>F5</Text>
        </TouchableOpacity>

        <TouchableOpacity style={ [styles.commandButton, { right: 100, top: 0 }] }
                          onPress={ () => sendCommand('audio_mute') }>
          <Image source={ require('../assets/vol_mute.png') } style={ [styles.commandButtonIcon] } />
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { right: 50, top: 0 }] }
                          onPress={ () => sendCommand('audio_vol_down') }>
          <Image source={ require('../assets/vol_down.png') } style={ [styles.commandButtonIcon] } />
        </TouchableOpacity>
        <TouchableOpacity style={ [styles.commandButton, { right: 0, top: 0 }] }
                          onPress={ () => sendCommand('audio_vol_up') }>
          <Image source={ require('../assets/vol_up.png') } style={ [styles.commandButtonIcon] } />
        </TouchableOpacity>
      </View>
    </>
  )
}

const SendRing = () => {
  const sendRing = async () => {
    await sendTcpData({
      type: 'ring',
      content: true,
    })
    Modal.show({
      title: '正在查找',
      content: (
        <Text>设备正在响铃...</Text>
      ),
      footer: (
        <View style={ modalStyles.button }>
          <Button onPress={ () => {
            sendTcpData({ type: 'ring', content: false })
            Modal.hide()
          } }>停止</Button>
        </View>
      )
    })
  }

  return (
    <Button onPress={ sendRing }>查找设备</Button>
  )
}

// syncer-desktop/src/views/Send.vue
<template>
  <div class="target">
    <h1>{{ targetName }}</h1>
    <a-button @click="disconnect">断开连接</a-button>
    <ReceiveHistory />
  </div>

  <div class="white-list">
    <a-checkbox :checked="isInWhiteList" @change="setIsInWhiteList(!isInWhiteList)">自动接受此设备的连接请求</a-checkbox>
  </div>

  <a-segmented v-model:value="type" class="select-type" :options="[
    { value: 'text', label: '发送文本' },
    { value: 'file', label: '发送文件' },
    { value: 'command', label: '发送指令' },
  ]" />

  <div v-show="type === 'text'" class="send-text">
    <a-textarea v-model:value="text" class="input-text" allow-clear placeholder="请输入要发送的文本"
                :auto-size="{ minRows: 3, maxRows: 10 }" />
    <a-button type="primary" :loading="sendingText" @click="sendText">发送</a-button>
  </div>

  <div v-show="type === 'file'" class="send-file">
    <a-upload-dragger class="input-file" :file-list="files" multiple
                      :before-upload="handleSelectFile" @remove="handleRemoveFile">
      <PlusOutlined class="icon" />
      <div>拖拽或选择要发送的文件</div>
    </a-upload-dragger>
    <a-button class="send-file-button" type="primary" :loading="sendingFile" @click="sendFile">发送</a-button>
  </div>

  <div v-show="type === 'command' && store.state.target.device === 'mobile'" class="send-ring">
    <a-button type="primary" @click="sendRing">查找设备</a-button>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { sendTcpData } from '@/service/tcpService'
import { useStore } from 'vuex'
import { PlusOutlined } from '@ant-design/icons-vue'
import { fileToBase64 } from '@/utils/file'
import { message, Modal } from 'ant-design-vue'
import ReceiveHistory from '@/components/ReceiveHistory.vue'
import { getStorage, setStorage, STORAGE_KEYS } from '@/utils/storage'

const store = useStore()

const targetName = computed(() => store.state.target?.name)
function disconnect() {
  sendTcpData({
    type: 'disconnect'
  })
  store.dispatch('disconnect')
}

const isInWhiteList = ref(false)
getIsInWhiteList()

function getIsInWhiteList() {
  const whiteList = getStorage(STORAGE_KEYS.WHITE_LIST) || {}
  isInWhiteList.value = whiteList[store.state.target.uuid] === true
}

function setIsInWhiteList(isInWhiteList) {
  const whiteList = getStorage(STORAGE_KEYS.WHITE_LIST) || {}
  if (isInWhiteList)
    whiteList[store.state.target.uuid] = true
  else
    delete whiteList[store.state.target.uuid]
  setStorage(STORAGE_KEYS.WHITE_LIST, whiteList)
  getIsInWhiteList()
}

const type = ref('text')

const text = ref('')
const sendingText = ref(false)
async function sendText() {
  if (!text.value)
    return
  sendingText.value = true
  await sendTcpData({
    type: 'text',
    content: text.value,
  })
  sendingText.value = false
  text.value = ''
  message.success('发送成功')
}

const files = reactive([])
const sendingFile = ref(false)
function handleSelectFile(file) {
  files.push(file)
  console.log(file)
  return false
}
function handleRemoveFile(file) {
  files.splice(files.indexOf(file), 1)
}
async function sendFile() {
  if (!files.length)
    return
  sendingFile.value = true
  const list = []
  for (const file of files) {
    const data = (await fileToBase64(file)).split(',')[1]
    list.push({ name: file.name, data })
  }
  await sendTcpData({
    type: 'file',
    content: list,
  })
  sendingFile.value = false
  files.length = 0
  message.success('发送成功')
}

async function sendRing() {
  Modal.info({
    centered: true,
    icon: null,
    title: '正在查找',
    content: '设备正在响铃...',
    okText: '停止',
    onOk: async () => {
      await sendTcpData({
        type: 'ring',
        content: false,
      })
    },
  })
  await sendTcpData({
    type: 'ring',
    content: true,
  })
}

</script>

<style scoped lang="scss" src="@/styles/Send.scss" />
