// syncer-desktop/src/components/ReceiveHistory.vue
<template>
  <a-button class="receive-history__show-button" type="text" @click="show">
    <template #icon>
      <FileTextOutlined />
    </template>
  </a-button>

  <a-modal v-model:open="visible" title="接收历史" class="receive-history" centered :footer="false">
    <div class="receive-history__head">
      <a-checkbox v-if="selecting" :checked="allSelected" @change="selectAll">全选</a-checkbox>
      <div v-else>共 {{ receiveHistory.length }} 条记录</div>
      <div class="receive-history__operation">
        <a-button @click="changeSelecting">{{ selecting ? '取消' : '选择' }}</a-button>
        <a-button v-if="selecting" type="primary" danger :disabled="!selectedList.length"
                  @click="deleteSelectedItems">删除</a-button>
      </div>
    </div>
    <div class="receive-history__list">
      <div v-for="(item, index) in list" :key="index" class="receive-history__item"
           @click="handleClickItem(item)">
        <a-checkbox v-if="selecting" v-model:checked="item.selected"></a-checkbox>
        <div class="receive-history__item-middle">
          <div class="receive-history__item-name">{{ item.name }}</div>
          <div class="receive-history__item-details">
            <a-tag>{{ formatTime(item.time) }}</a-tag>
            {{ item.path }}
          </div>
        </div>
        <RightOutlined class="receive-history__item-icon" />
      </div>
      <a-button v-if="hasMore" class="receive-history__show-more" type="link" @click="showMore">加载更多</a-button>
      <a-divider v-else>
        <span class="receive-history__no-more">没有更多了</span>
      </a-divider>
    </div>
  </a-modal>
</template>

<script setup>
import { FileTextOutlined, RightOutlined } from '@ant-design/icons-vue'
import { computed, reactive, ref } from 'vue'
import { getStorage, setStorage } from '@/utils/storage'
import dayjs from 'dayjs'
import { shell } from 'electron'
import fs from 'fs'
import { message } from 'ant-design-vue'

const visible = ref(false)
const receiveHistory = reactive([])
const pageIndex = ref(1)
const list = computed(() => receiveHistory.slice(0, pageIndex.value * 20))

/** 打开接受历史窗口 */
function show() {
  visible.value = true
  pageIndex.value = 1
  const temp = getStorage('receiveHistory') || []
  receiveHistory.length = 0
  receiveHistory.push(...temp.map(item => ({ ...item, selected: false })))
}

const hasMore = computed(() => receiveHistory.length > pageIndex.value * 20)

/** 加载更多 */
function showMore() {
  pageIndex.value++
}

const selecting = ref(false)
const selectedList = computed(() => list.value.filter(item => item.selected))
const allSelected = computed(() => list.value.length && selectedList.value.length === list.value.length)

/** 选择、取消选择 */
function changeSelecting() {
  if (!selecting.value) {
    selecting.value = true
    list.value.forEach((item) => {
      item.selected = false
    })
  } else {
    selecting.value = false
  }
}

/** 全选、取消全选 */
function selectAll() {
  const selected = !allSelected.value
  list.value.forEach((item) => {
    item.selected = selected
  })
}

/** 删除选中的记录 */
function deleteSelectedItems() {
  const temp = receiveHistory.filter(item => !item.selected)
  receiveHistory.length = 0
  receiveHistory.push(...temp)
  setStorage('receiveHistory', receiveHistory)
  selecting.value = false
}

/** 时间戳格式化 */
function formatTime(time) {
  return dayjs(time).format('YYYY-MM-DD HH:mm')
}

/** 处理记录点击事件 */
function handleClickItem(item) {
  if (selecting.value) {
    item.selected = !item.selected
    return
  }
  // 打开文件路径
  const path = item.path + '\\' + item.name
  if (!fs.existsSync(path)) {
    message.error('文件不存在')
    return
  }
  shell.showItemInFolder(path)
}
</script>

<style lang="scss" scoped>
@import "@/styles/theme.scss";

.receive-history__show-button {
  color: $secondary-text-color;
}

.receive-history__head {
  display: flex;
  align-items: center;
  padding: 12px 0;
}

.receive-history__operation {
  margin-left: auto;
  display: flex;
  align-items: center;
  gap: 4px;
}

.receive-history__list {
  display: flex;
  flex-direction: column;
  height: calc(60vh - 56px);
  padding: 0 24px;
  margin: 0 -24px;
  overflow-y: auto;
}

.receive-history__item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 8px 24px;
  margin: 0 -24px;
  cursor: pointer;

  &:hover {
    background: $bg-color-grey;
  }
}

.receive-history__item-middle {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  width: 0;
}

.receive-history__item-name {
  margin-bottom: 4px;
  font-weight: bold;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.receive-history__item-details {
  color: $tip-text-color;
  font-size: 13px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.receive-history__item-icon {
  color: $tip-text-color;
}

.receive-history__show-more {
  margin: 0 auto;
  color: $brand-color;

  &:hover {
    color: $hover-color;
  }
}

.receive-history__no-more {
  color: $tip-text-color;
  font-size: 12px;
}

</style>

// syncer-mobile/src/components/ReceiveHistory.jsx
import { getStorage, setStorage, STORAGE_KEYS } from '../utils/storage'
import { useEffect, useMemo, useState } from 'react'
import { ScrollView, Text, ToastAndroid, TouchableOpacity, View } from 'react-native'
import { Button, CheckBox } from '@rneui/themed'
import styles from '../styles/ReceiveHistoryStyles'
import Icon from 'react-native-vector-icons/AntDesign'
import theme from '../styles/theme'
import RNFS from 'react-native-fs'
import moment from 'moment'
import FileViewer from 'react-native-file-viewer'
import { Modal, modalStyles } from './Modal'


const ReceiveHistory = () => {
  const [receiveHistory, setReceiveHistory] = useState([])
  useEffect(() => {
    getStorage(STORAGE_KEYS.RECEIVE_HISTORY).then((res) => {
      const temp = res?.map(item => ({ ...item, selected: false })) || []
      setReceiveHistory(temp)
    })
  }, [])
  const selectedList = receiveHistory.filter(item => item.selected)
  const allSelected = useMemo(
    () => receiveHistory.length && selectedList.length === receiveHistory.length,
    [selectedList.length, receiveHistory.length]
  )
  const [pageIndex, setPageIndex] = useState(1)
  const hasMore = useMemo(
    () => receiveHistory.length > pageIndex * 20,
    [receiveHistory.length, pageIndex]
  )

  const [selecting, setSelecting] = useState(false)
  const [path] = useState(RNFS.DownloadDirectoryPath + '/Syncer/')

  function handleSelectItem(i) {
    const temp = receiveHistory.slice()
    temp[i].selected = !temp[i].selected
    setReceiveHistory(temp)
  }

  function selectAll() {
    const temp = receiveHistory.slice()
    temp.forEach((item) => { item.selected = !allSelected })
    setReceiveHistory(temp)
  }

  async function deleteSelectedItems() {
    const remainList = receiveHistory.filter(item => !item.selected)
    setReceiveHistory(remainList)
    await setStorage(STORAGE_KEYS.RECEIVE_HISTORY, remainList)
    setSelecting(false)
  }

  async function handlePressItem(name, index) {
    if (selecting) {
      handleSelectItem(index)
      return
    }
    if (!await RNFS.exists(path + name)) {
      ToastAndroid.show('文件不存在', ToastAndroid.SHORT)
      return
    }
    await FileViewer.open(path + name)
  }

  const listItems = receiveHistory.slice(0, pageIndex * 20).map((item, index) => (
    <TouchableOpacity key={ index } style={ styles.item } activeOpacity={ 0.5 }
                      onPress={ () => handlePressItem(item.name, index) }>
      {
        selecting && (
          <CheckBox checked={ item.selected } size={ 20 } onPress={ () => handleSelectItem(index) } />
        )
      }
      <View style={ styles.itemDetails }>
        <Text style={ styles.fileName } numberOfLines={ 1 } ellipsizeMode="middle">{ item.name }</Text>
        <Text style={ styles.time }>{ moment(item.time).format('YYYY-MM-DD HH:mm') }</Text>
      </View>
      <Icon name="right" size={ 14 } color={ theme.tipTextColor } />
    </TouchableOpacity>
  ))
  return (
    <>
      <View>
        <View style={ styles.operation }>
          {
            selecting ? (
              <CheckBox
                checked={ allSelected }
                size={ 20 }
                title="全选"
                textStyle={ styles.selectAll }
                onPress={ selectAll } />
            ) : <Text>共 { receiveHistory.length } 条记录</Text>
          }
          <View style={ styles.operationRight }>
            <Button type="outline" buttonStyle={ styles.button } titleStyle={ styles.select }
                    onPress={ () => setSelecting(!selecting) }>{ selecting ? '取消' : '选择' }</Button>
            {
              selecting && (
                <Button onPress={ deleteSelectedItems }
                        disabled={ selectedList.length === 0 } color="error"
                        buttonStyle={ styles.button } titleStyle={ styles.delete }>删除</Button>
              )
            }
          </View>
        </View>
        <Text style={ styles.path }>{ path }</Text>
        <ScrollView contentContainerStyle={ styles.list } style={ styles.listWrap }>
          { listItems }
          {
            hasMore ? (
              <Button type="clear" containerStyle={ styles.showMore }
                      onPress={ () => setPageIndex(pageIndex + 1) }>显示更多</Button>
            ) : <Text style={ styles.noMore }>没有更多了</Text>
          }
        </ScrollView>
      </View>
    </>
  )
}
export default ReceiveHistory

export function showReceiveHistory() {
  Modal.show({
    title: '接收历史',
    content: <ReceiveHistory />,
    footer: (
      <View style={ modalStyles.button }>
        <Button onPress={ Modal.hide }>关闭</Button>
      </View>
    )
  })
}
